### ISSUE TITLE
Differential Flux conversion factor error

### ISSUE THREAD

**Issue by deividribeiro** [Eventdisplay/Eventdisplay#29]
Some refactoring missed the conversion of the variable fAlpha to fSpectralIndex. The `fAlpha` in the following two lines should be `fSpectralIndex`: 
https://github.com/Eventdisplay/Eventdisplay/blob/172e9054514f8fb69142491e20b356a4d022c6ce/src/VFluxDataPoint.cpp#L254

https://github.com/Eventdisplay/Eventdisplay/blob/172e9054514f8fb69142491e20b356a4d022c6ce/src/VFluxDataPoint.cpp#L270

**Comment by GernotMaier** [comment]
Great catch - thanks!

Fixed with commit cd73e8f
