### ISSUE TITLE
splitVBF does not work correctly for VERITAS simulation files

### ISSUE THREAD

**Issue by dawucsc** [Eventdisplay/Eventdisplay#89]
The VERITAS simulation files have an structure that is assumed by VEGAS in processing them and not respected by the existing version of splitVBF. 

The normal structure of the file is a block of ten events with raw event type 10 (I assume these are pedestal events) followed by some number of events with raw event type 1.  The time of the first of the type 10 events is 02:00:00 and the time of the next nine events is 02:00:01.  The times of the type 1 events are all later.  While I have not dug into the VEGAS code, it appears to decide the span of the run based on the time of the first event and the last event, not based on the minimum time and the maximum time.  So if the point at which the run gets split does not land in such a way that the type 10 events are at the beginning of the run, their times all end up out of bounds, and various hell breaks loose.

I have created a new version of the splitting code splitSimVBF.cpp that looks for the start of the next type 10 event block before closing out one of the sub runs.   For several simulations files that we had not been able to process successfully with VEGAS after splitting them, this fixed the problem.

I have attached the splitSimVBF.cpp code, which compiles exactly the same as splitVBF.cpp (and needs instructions added in the makefile).  I have also attached a version of splitVBF.cpp where the brief comment in the header is changed.

[splitfiles.tar.gz](https://github.com/Eventdisplay/Eventdisplay/files/6062855/splitfiles.tar.gz)

**Comment by RaulRPrado** [comment]
Thanks for that, @dawucsc 

It seems like we only need your splitSimVBF, instead of also keeping the old splitVBF.
I will replace splitVBF by your code and open a PR.

**Comment by dawucsc** [comment]
@RaulRPrado I think it makes sense to keep both versions, since the splitSimVBF would not necessarily work for splitting files that do not have the same structure of events with raw event type == 10.

**Comment by RaulRPrado** [comment]
Ok @dawucsc, that makes sense.

I updated the split_vbf branch with your input.

@GernotMaier, please have a look and merge the PR if it's all fine for you.

**Comment by GernotMaier** [comment]
Issue fixed with pull request #90
